const { contextBridge, ipcRenderer } = require('electron');

// Expose MP+ APIs
contextBridge.exposeInMainWorld('mpplus', {
  saveUrl: async (url) => ipcRenderer.invoke('save-url', url),
  loadUrl: async () => ipcRenderer.invoke('load-url'),
  openUrl: async (url) => ipcRenderer.invoke('open-url', url),
  fetchStudentLevel: async (classSubdomain) => ipcRenderer.invoke('fetch-student-level', classSubdomain)
});


// -- Context Menu --
window.addEventListener("contextmenu",e=>{try{e.preventDefault();let t=e.target,n=t&&t.nodeName?t.nodeName.toUpperCase():"",r=!!(t&&(t.isContentEditable||"INPUT"===n||"TEXTAREA"===n)),o=window.getSelection?window.getSelection().toString():"",a=null,l=null;try{let c=t.closest?t.closest("a"):null;c&&c.href&&(a=c.href)}catch(s){}try{t&&t.tagName&&"img"===t.tagName.toLowerCase()&&t.src&&(l=t.src)}catch(i){}ipcRenderer.invoke("show-context-menu",{x:e.clientX,y:e.clientY,selection:o,isEditable:r,nodeName:n,linkURL:a,srcURL:l})}catch(m){console.error("preload contextmenu handler error",m)}});

// -- Inject Branding --
let BRANDING_CODE=null,lastBlobUrl=null,brandingLoaded=!1;async function fetchBrandingFromMain(){try{let e=await ipcRenderer.invoke("get-branding-code");e&&e.ok&&"string"==typeof e.code?(BRANDING_CODE=e.code,brandingLoaded=!0,console.log("[MP+] Branding code loaded from main process")):console.error("[MP+] failed to load branding code from main:",e&&e.error)}catch(n){console.error("[MP+] ipc invoke error get-branding-code:",n)}}function createAndAppendBrandingScript(e){if(e&&!document.getElementById("mpplus-branding"))try{let n=new Blob([e],{type:"text/javascript"}),t=URL.createObjectURL(n),r=document.createElement("script");if(r.id="mpplus-branding",r.src=t,r.setAttribute("data-mpplus","1"),(document.documentElement||document.head||document.body).appendChild(r),lastBlobUrl)try{URL.revokeObjectURL(lastBlobUrl)}catch(d){}lastBlobUrl=t,console.log("[MP+] injectBranding.js injected via blob")}catch(a){console.error("[MP+] error injecting branding script:",a)}}function ensureBrandingInjected(){if(!brandingLoaded){setTimeout(ensureBrandingInjected,100);return}document.getElementById("mpplus-branding")||createAndAppendBrandingScript(BRANDING_CODE)}function setupAutoReinject(){ensureBrandingInjected();let e=history.pushState,n=history.replaceState;history.pushState=function(...n){let t=e.apply(this,n);return setTimeout(ensureBrandingInjected,60),t},history.replaceState=function(...e){let t=n.apply(this,e);return setTimeout(ensureBrandingInjected,60),t},window.addEventListener("popstate",()=>setTimeout(ensureBrandingInjected,60));let t=null,r=new MutationObserver(()=>{t&&clearTimeout(t),t=setTimeout(()=>{ensureBrandingInjected()},120)});try{r.observe(document.documentElement,{childList:!0,subtree:!0})}catch(d){setTimeout(()=>{try{r.observe(document.documentElement,{childList:!0,subtree:!0})}catch(e){}},200)}document.addEventListener("DOMNodeRemoved",e=>{e.target&&"mpplus-branding"===e.target.id&&setTimeout(ensureBrandingInjected,60)})}fetchBrandingFromMain().finally(()=>{"loading"===document.readyState?window.addEventListener("DOMContentLoaded",setupAutoReinject,{once:!0}):setupAutoReinject()});

// -- Dismiss Browser Warning --
!function(){function e(){try{let e=Array.from(document.querySelectorAll("button")),t=e.find(e=>e.textContent.includes("Okay"));if(t)return t.click(),console.log("[MP+] Dismissed browser warning"),!0}catch(n){console.error("[MP+] Error clicking button:",n)}return!1}function t(){if(!document.body){setTimeout(t,100);return}e();let n=new MutationObserver(e=>{for(let t of e)if(t.addedNodes.length){for(let n of t.addedNodes)if(1===n.nodeType){if(n.matches&&n.matches("button")&&n.textContent.includes("Okay")){n.click();return}if(n.querySelector){let r=n.querySelector("button");if(r&&r.textContent.includes("Okay")){r.click();return}}}}});n.observe(document.body,{childList:!0,subtree:!0});let r=setInterval(()=>{e()&&clearInterval(r)},500);setTimeout(()=>clearInterval(r),1e4)}"complete"===document.readyState?t():window.addEventListener("load",t,{once:!0})}();